name: bookshelf
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  envied_flutter: ^0.3.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^14.0.2
  signals_flutter: ^5.2.0
  supabase_flutter: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  go_router_builder: ^2.6.1

flutter:
  uses-material-design: true
